# Generated by Django 2.2.28 on 2025-03-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0004_auto_20250324_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
