# Generated by Django 5.1.7 on 2025-03-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ROS_App",
            "0008_alter_book_id_alter_category_id_alter_category_name_and_more",
        ),
        ("ROS_App", "0008_alter_book_id_alter_category_id_alter_review_id_and_more"),
    ]

    operations = []
