# Generated by Django 5.1.7 on 2025-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ROS_App", "0009_auto_20250326_1103"),
        ("ROS_App", "0009_merge_20250326_1127"),
    ]

    operations = []
