# Generated by Django 2.2.28 on 2025-03-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0014_auto_20250326_1713'),
        ('ROS_App', '0014_auto_20250326_1626'),
    ]

    operations = [
    ]
