# Generated by Django 5.1.7 on 2025-03-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ROS_App", "0015_merge_20250326_1728"),
        ("ROS_App", "0017_auto_20250326_2252"),
    ]

    operations = []
