# Generated by Django 2.2.28 on 2025-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0018_merge_20250327_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
