# Generated by Django 2.2.28 on 2025-03-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0019_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
