# Generated by Django 2.2.28 on 2025-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0020_remove_book_categories'),
        ('ROS_App', '0019_alter_book_id_alter_category_id_alter_review_id_and_more'),
    ]

    operations = [
    ]
