# Generated by Django 2.2.28 on 2025-03-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROS_App', '0020_auto_20250327_1441'),
        ('ROS_App', '0022_auto_20250327_1523'),
    ]

    operations = [
    ]
